# Typed surface of the z3-solver Python API used by ppy_rev.solver.z3_backend.
# z3-solver ships without type information; only the calls ppy-rev makes are declared.

import ctypes

class Context:
    def __init__(self) -> None: ...
    def ref(self) -> ctypes.c_void_p: ...

class Ast(ctypes.c_void_p): ...

class AstRef:
    def sexpr(self) -> str: ...
    def as_ast(self) -> Ast: ...

class ExprRef(AstRef):
    def __eq__(self, other: object) -> BoolRef: ...
    def __ne__(self, other: object) -> BoolRef: ...

class BoolRef(ExprRef): ...

class BitVecRef(ExprRef):
    def size(self) -> int: ...
    def __add__(self, other: BitVecRef) -> BitVecRef: ...
    def __sub__(self, other: BitVecRef) -> BitVecRef: ...
    def __mul__(self, other: BitVecRef) -> BitVecRef: ...
    def __truediv__(self, other: BitVecRef) -> BitVecRef: ...
    def __and__(self, other: BitVecRef) -> BitVecRef: ...
    def __or__(self, other: BitVecRef) -> BitVecRef: ...
    def __xor__(self, other: BitVecRef) -> BitVecRef: ...
    def __lshift__(self, other: BitVecRef) -> BitVecRef: ...
    def __rshift__(self, other: BitVecRef) -> BitVecRef: ...
    def __invert__(self) -> BitVecRef: ...
    def __neg__(self) -> BitVecRef: ...
    def __lt__(self, other: BitVecRef) -> BoolRef: ...
    def __le__(self, other: BitVecRef) -> BoolRef: ...

class BitVecNumRef(BitVecRef):
    def as_long(self) -> int: ...

class CheckSatResult:
    def __init__(self, r: int) -> None: ...

sat: CheckSatResult
unsat: CheckSatResult
unknown: CheckSatResult

class ModelRef:
    def eval(self, t: BitVecRef, model_completion: bool = ...) -> BitVecNumRef: ...

class Solver:
    solver: ctypes.c_void_p
    def __init__(self, ctx: Context | None = ...) -> None: ...
    def add(self, *args: BoolRef) -> None: ...
    def push(self) -> None: ...
    def pop(self, num: int = ...) -> None: ...
    def check(self, *assumptions: BoolRef) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...
    def set(self, key: str, value: int | bool | str) -> None: ...
    def reason_unknown(self) -> str: ...
    def to_smt2(self) -> str: ...

def Z3_solver_check_assumptions(
    a0: ctypes.c_void_p, a1: ctypes.c_void_p, a2: int, a3: ctypes.Array[Ast]
) -> int: ...
def BitVec(name: str, bv: int, ctx: Context | None = ...) -> BitVecRef: ...
def BitVecVal(val: int, bv: int, ctx: Context | None = ...) -> BitVecNumRef: ...
def Bool(name: str, ctx: Context | None = ...) -> BoolRef: ...
def BoolVal(val: bool, ctx: Context | None = ...) -> BoolRef: ...
def And(*args: BoolRef) -> BoolRef: ...
def Or(*args: BoolRef) -> BoolRef: ...
def Not(a: BoolRef) -> BoolRef: ...
def Xor(a: BoolRef, b: BoolRef) -> BoolRef: ...
def If(a: BoolRef, b: BitVecRef, c: BitVecRef) -> BitVecRef: ...
def ULT(a: BitVecRef, b: BitVecRef) -> BoolRef: ...
def ULE(a: BitVecRef, b: BitVecRef) -> BoolRef: ...
def UDiv(a: BitVecRef, b: BitVecRef) -> BitVecRef: ...
def URem(a: BitVecRef, b: BitVecRef) -> BitVecRef: ...
def SRem(a: BitVecRef, b: BitVecRef) -> BitVecRef: ...
def LShR(a: BitVecRef, b: BitVecRef) -> BitVecRef: ...
def Concat(a: BitVecRef, b: BitVecRef) -> BitVecRef: ...
def Extract(high: int, low: int, a: BitVecRef) -> BitVecRef: ...
def ZeroExt(n: int, a: BitVecRef) -> BitVecRef: ...
def SignExt(n: int, a: BitVecRef) -> BitVecRef: ...
